[tool.poetry]
name = "invoices"
# develop = true
version = "0.1.0"
description = ""
authors = ["Matthew McKenna <mattheweb.mckenna@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# [tool.poetry.scripts]
# package, module, function
# invoice-extract = "invoicedb.cli:main"

[tool.black]
line-length = 88
# the minimum supported Python version for Black's output
target-version = ['py310']

[tool.pytest.ini_options]
minversion = "7.1.2"
# -ra:
  # -r: display a "short test summary info"
  # -a: "all except passes"
addopts = "-ra -v"
testpaths = [
    "tests",
]
