[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "invoices"
authors = [{name = "Matthew McKenna"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
# dynamic = ["version"]
version = "0.1.0"
dependencies = ["click"]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
invoices = "invoices.cli:cli"
